
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 14;
  public static final int UMINUS = 23;
  public static final int LPAREN = 25;
  public static final int SEMI = 31;
  public static final int INT = 5;
  public static final int MINUS = 20;
  public static final int RPAREN = 26;
  public static final int NOT = 16;
  public static final int AND = 18;
  public static final int LT = 12;
  public static final int OR = 17;
  public static final int BOOL = 4;
  public static final int COMMA = 24;
  public static final int DIV = 22;
  public static final int NUM = 33;
  public static final int PLUS = 19;
  public static final int ASSIGN = 9;
  public static final int IF = 2;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int error = 1;
  public static final int LCURLY = 29;
  public static final int VOID = 7;
  public static final int EQ = 10;
  public static final int ERROR = 35;
  public static final int GTE = 15;
  public static final int LBRACK = 27;
  public static final int RCURLY = 30;
  public static final int TRUTH = 34;
  public static final int TIMES = 21;
  public static final int ELSE = 3;
  public static final int RBRACK = 28;
  public static final int WHILE = 8;
  public static final int NE = 11;
  public static final int GT = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "BOOL",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "ASSIGN",
  "EQ",
  "NE",
  "LT",
  "GT",
  "LTE",
  "GTE",
  "NOT",
  "OR",
  "AND",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "UMINUS",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LCURLY",
  "RCURLY",
  "SEMI",
  "ID",
  "NUM",
  "TRUTH",
  "ERROR"
  };
}

